apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sHVC99qJPCCsPAFOLFHBBAI/EEkTvnkMUeK0Qobyp5og5pe+2G/p3g==,iv:Ny7cipWHq+BKgNVE3kcpKvrPisWnwVgC9gPNxRvkBLg=,tag:OzSUZrXqjNy2BVoqrlPT7A==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK1NkS0FlN0hqaUo4QU0v
        cUFVT0tpRW5OMEQzTnkrVEsvZlNuYnc2dmhnCnFIbFIzNkhIenI0U3dOYktlaHpB
        WllRN1dJOGFsYTZ5NUZVUGhseDR4VFUKLS0tIGFLcE9pT0VTTGFVRi83dFhSRGZI
        NzlSVnRxYVE3UDR2NG8xRkYySFZOeDAK97g3Ol8p74wumxOMtWhYCQ1SHaTMTgiE
        w0eaHSfpxz54BIGAXE78fEnT+XIzUL0a24ZYT/XNloXvUb7LmcYt/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:36:23Z"
  mac: ENC[AES256_GCM,data:W4rMYU4KBaKvUtcWJ4iYud0DML2aVVKf7HnJoFjTGwuLMFv0NQ4I1JO7ymUMJG8ssDWYhQ3eeNN2v9GQfKB7HCfaY+i+s4w9yW06okVr5RGQzT5Ify6jz72YAIMAgOF+IahQ+wpVLrT0RwpMeOOXvPhv1YFNTRSzsUbhH8c7w4s=,iv:XzudB2/xWYqV3p3bKHwkoH1G5Q8hIzJk9jk+KwTnh20=,tag:RhQb28xMS5ay/atpq/BD8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
