apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jWuEpYUjpGhZu3l5OPA=,iv:Tpejo5N6Vcv+g8XuGvTudN543cFGrykMu54DDMccf1U=,tag:UsCW+02h+SAscGIk1e5C0A==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dEROeHA5bVZ2TXRqeUtr
        dXNOM1orbTVQMXAxekNuNys4TzMvWGRzd1I4Clhyc3dBcFpycDMrR1BhTnRSZWxL
        MXBvV0F0NXZ4RGJ0T0I3bE5LN3Azb1kKLS0tIFZiZ1p3QURVMmp1QmdkYVBmajJk
        K2xINlB3OTU1aTJFeHA2NHpBM1NxOVEKPjdn2zvjB1kYwXwsg2NgF5VIS2rRk/3Y
        bzK1JHzkm+TlzoOt3UjP6E14yCLAlMmATnIQOASb5zpSbAPkEhWCTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:36:23Z"
  mac: ENC[AES256_GCM,data:k6usrfWrk94DtS2p1tcfYJRP/b7+9vMnAfNVtV2+lZnr5aLU0UO4Ff9OLhTUzU5lZmFWxRYVPVNJxobjBlJIEyQBmnA3du94x6KlPccNakUckWczDUTySz7VdBLhQQZNVVljQuHHsX2F52v0xYU1AaaphlYSqA30vqgreOh/vDg=,iv:nRJp0tnHABS3ouTkOgyXZMZ7O+bn0K8IBISOdTbXfZs=,tag:oJVcF9yFZv3ZDeqBb5g1Lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
