apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:OFbfXHq3x2vSqUgugwZN5LogagS0BaecbC7X/TPRD3I=,iv:pegANfBnAwqAEkG5URu+5gDUVk5yQSmJN5g5qD6dHY8=,tag:4Fz8ElKxPm5pIT12IhKngw==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmemlsMXdYZnBpNHZKdFRu
        aDFGMlNFbk9XWnRzNDNXQXVhRk8yQXpoRVdZCkJ4NGZZb0xubzMzTE1EV3pwREpR
        UTQ0V0dzMWtaR0x6YUE1VkY5QUxCMDgKLS0tIG1JbUJOS3psYW15Rk9NSkxwQzBP
        bEtPZkd4eXY5MEgzQm53MGkxdUNNME0KcfgrTwbhubdHZrR3bZsXPgfaWy6nubbV
        BksyyJB2MGSNkenaZUAoDI7jYgZjS22uVVnOz9l0ZsdKsdHmCC6q4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:03:45Z"
  mac: ENC[AES256_GCM,data:qbHRDHNpbP5YQhmV+tftiq/x5IDlym4Rb15G/tYtfBDtTpPdtcN5nzoxTfTiA9/DsvJHN0aJk9yBLqRgvNYBsmCwqaGWk19aTxP08NwkfpahTtFm7h/uUwMjTl3oU3RmkWmXDTI8zQSw2sL+U7wCwKELrxRE1Mw86yqeXSkJTJA=,iv:vXiMqiZfGclpUxrCYj3EbIQLDJqIvD9+i9lvsuLVQIs=,tag:rzeSG7uDulKTdcHmOGDkTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
