apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nzTjOEsDVsYjdmNxCRA4qikYO9BfOKMxN5OGKMf49yk=,iv:78rSJeTINhcqLAhLN/om0ikFgPIIjCH43GY6Gu9n6BI=,tag:IbBlV7+xN8PSk66s359YpQ==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYkx2UGhoekJNQWpvbnds
        aTlUbGtWRzNuWXFiWHRmQnVkRFM1QlNDVWhjCkFRblZIeWVFRlNrY1orakZrR0t3
        Uy9zYkNJVXNqSU1OMVZBVGxwRmY5Q00KLS0tIHZBOGtrWXVuWVAwV1RVNU1ELzh0
        ZGNtcnNNUDNvT2Y4eGlpVWRRbjhwWUkKmolARkZzX5FqvH3G3+6ksE4kPQc4ECZS
        SGrFVlMVX1fO4n2xMKlnoMIlX+bho4ctlYigtgfsc+cL0nVn/TTw6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:36:23Z"
  mac: ENC[AES256_GCM,data:+6NVZp+aH5PJDcd8cm0hiEwy5WrF9Xl6+HFb8TkxqLms4vXfjjFv41u5MfugKJG+FiZn9A5OUai9hHyzIJUEjALQxHdcrw6tdde2zt+JM8unT16PncE1rIQ5OVGdhX72fgntTIFFXZdCQnldXPaazefG9LU0xsXHXC8yfS7SHuU=,iv:xCMCykZhcShde/b5Bjv1W0tIbPq+SgyWpXG16ZEZfbg=,tag:5YxPJWa7EzKRW5U+oic+2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
