apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1PHejatKt4iRQNEiz3J5cQc964HA0W81P7UVriDiG+zgezpDV0aHwwygk9jCDThAyplm6+tWY53hq5ZKJXagN8UdRkyJQdxcHqqRpGKbwU4a4EiPwBQt2GxSOanm2j5iITXw1gGibZ0i8OKzYQmqodd4Xwn+uIEzDu9kLcZlvUlF26t3XE8AwYTIUHiLuRBiMpabiYK5OLgs1fE4t2EzMXK40oemNybyFke4yXMJO1D5jZW+,iv:9cnAA2b6HSYDybcFtt+czB0SLW+g7LhkL3YJCRhF6ck=,tag:W8L9aDT/j7lfOfSKJsdE4A==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTFJaN2w3ZytaeDN2ZUtY
        d1IxZVNsbW9FaWZIQ2xWWmlCa1RRejd1cVRjCklWSDd3VWhhc1dDOTBOZzJHclZE
        REJBRjVubWNTVUV5L3VuTEVJU3JJeTgKLS0tIGhkTGlZL28zUzdZV2pQVm9NRlVk
        L0Nha2NhUlE3WENvbWpoVVZCTTJVeWsKNbtuXJHDb4+vGewn4T8EfhXpCh4UsLo3
        gAvbCDKZ4HpXNVAYCveAmZf4VCzkZ7T1vJBeEkFO6bdw5+2j0yu7tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:36:23Z"
  mac: ENC[AES256_GCM,data:Gq2Gg4U7AvKnUzSrZvi8Hbfdo9BEkKaqt6raXSqjreDzof1LqPStSbX7ouHZjuFktdDjZuAGOmldhUepfQ+3baIpkGYW0LAn+B6vE6QVIx4GH0HgT3VB000e1qkRKWFDHK1pMQLyPonZs4dT7bIPr6fzEpwKEbBj85e8Zap05W8=,iv:nxeApFCqSM8ZOiBXaT682rGCHf2y+1lyqjF4s9FnWSM=,tag:JXRaSz7Pw7+i7/qlgZsi4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
