apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:96yeCvDOcat+qfPpUgh1YG5SCKiUHB5V74u71s9COeY7qNApdwP+Clo2tkX9cMVcdG6uW0N012O+PVx6N4NO1cRQTBKD2J9H3HuYXG1reB9UO9vamR89lfzgXCqA3rlZ8J3AaKSwKr4DtCVnUWzqmwb2w3HDcDFYdIKLEOz3QoazA17rGTFwvD6Yj424NaNMcAAb2tnt0TY6T3JYdzfGOW6rwuGyqLfF4Cmc7IV08mv1MBWs,iv:eBVNeMbS2iirfcsjUEjqxvNadasmm3fTtrw/wTbNpbQ=,tag:L5WFeHV+52p/4ovCpTHlHw==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVDBDSzFUbFBPOUo5SGRF
        ejlhT0VFYzhWbElYNkovaUUvZDNiUlA2UXdRCkpoSmd3Z0FpUnlYZnRnOEkvSzNy
        a1VZYnk4YWtHYlJodGRMVWc4bldRWEUKLS0tIEhzSjhkU29Za282UGFwdHJBVXpR
        N1FrTVZWb1pvWjhrTXNxelNVOTNnMWcKhLhFCEOGM9NwSEGRUt6rVBdAcbWSMtqS
        afhjytmaOSed5oU1WIpGlLPm6HVx2++fVfxjjwdUXzgrCsCGU98Tkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:03:45Z"
  mac: ENC[AES256_GCM,data:5tI41spGExvOgo37soHm+Owr5Im/PlCih/c8UxbJ26Y2XhAAG3W/5KZTH8BgGKMce2ynoYWyNF/diS40SgWXU0RfhsD4WwQIDt5o1X2O68DZHcOEomI/zNspUF1pXyaoDZWr2rxyw+zysEYtWuL5lgug07wQwBFpvnuyj8V5amQ=,iv:TR6Zrwib+Pb3Y5S0OpX3G4ml92gpwOJ6AFDfa6morMA=,tag:p51LXtxinPV/El5shURkig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
