apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fqgfzrLzFzDAf6GtmHWmRoxmQum30pMOqDPlo6KWOlZeLzuLVr+wKQ==,iv:M6TnCyid5KkP5f70ToSUYrAYDVWnkpW6cli2ZXG6GO8=,tag:cf3KJTY1M6OzCCWLt7TUiQ==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYTZNRk9IL0hiVUhBc1l2
        dnJzcTJZbmdoc1RIRVNYeEJ0R3B4UG1LL0ZvCmdUbnpTVlVkTnZqVi82WWhXZy83
        L0VNNGZaSjU4cFdOZWFaQnNYLzd5a1kKLS0tIFErTHA5c1Nob3o4emFYS0V4QTNT
        N2NmYWhML0l4TEZXMENmMkVQRWo4MGcKTwQvE5oUghf+EGebhDmSslWNrHgzonxP
        xk6PjC5rH0FQMz2/1/Zvr4M0HXS+s5TIzgAyAH+u+CSfUT2UnhQvvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:36:22Z"
  mac: ENC[AES256_GCM,data:nAmu2tA6Ix/RGv2z5ga3pduZmg5iLhsIfpmopU/GUrTt3aFgRtq1RKQTvQEhEw9k7AQyo19MgWvGaTyLhxbnk5qaomKNUdbb3wyPAORrQz+K6M7dR00Z8+xzsAcOQNE+uYJPk+aj7vV9ks/Ft6scvrpXvmDcOaRaGazgMdeN6gE=,iv:FWSvxR+3KVEr9RZC5hYfnlbjzbFOOl4EYVlNztkghNo=,tag:MNyCRR8UuWTI8mge21Vfeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
