apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uvAyVcXecNeQh4UGw5aTm2ZKkbj/EjvseuvDFPJ5PRFMkWmjFNWp6w==,iv:b7P9IvpihYm8t25b+GUe6aJPDMY5ZQ700hOz95FB+oU=,tag:wX8l6d1ra0tn1nBFtlmIhA==,type:str]
sops:
  age:
    - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN25TK2FYYmZ1L0dxRGxD
        VnM4d3IraE9iM09MTElldTM3R3NiTmdJQkNnCkJzbEljbzgxT3d2RGkwSmkzZ01i
        ZjJTdEplY2VRWFo0QmdGMm55bzdwRlUKLS0tIEVhbGN0RDlTQzAxcFJoaWtya0p1
        a2ZRNjJ0SGJIbVB2V04xMUJ5VFRRWlEKAsDDpmzmxkr1kVnLxx6BjUUV0cX3vpXM
        PQIuWSSkh3bU8pnwLftgU/cqS6BATDOY+OJ7DJtg1zYJu53mAhT9dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T18:03:45Z"
  mac: ENC[AES256_GCM,data:HLoNvCWGuc2qC9FlJl7o0AzSGzuLJcfQuwW7+N3IIpkFjIHJ/dUH6EfuzA9aeLl4un3LvCMnk62bFk2NT5lagNuT36zUzF6zgfg5LWe3VNQ5oynOgonQVA9HuxtRMdrY9uKi5IO2Rj6xKGWORw+iFkuyWCCgtcWX4wneNmcIgJw=,iv:dev+bR4bHQvngIO2hKsh12DpjlpxhVCw8YZR3m1ClmI=,tag:qIBSTLovYHP3bW+i3G/jfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
