apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    #ENC[AES256_GCM,data:DcpySvc3uahCyxpnip5xOf5DU4Mqbp+4d53w5AIZSDp9KWbjSIQaLsxnW33K/2IFiiKtzGk6i9/ekkB5XziBlCWx9fivh08eOi9oD8h5mtlIN9E=,iv:BRKTXubsAGz1F09W9jMB08vf/L4TXeKGI8jC1Ap3F9s=,tag:eQCF1LO5lQzeiWK1QJ6GjA==,type:comment]
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:gF9miAs1NcrR/T+c5pER+kARAsNmW0305bZaEhiCH/4=,iv:NWBzwvA1w7Zo3aVcTUf11++Sa+OIh3Ue+hbkBuCtHZ4=,tag:QwPJD7SaEU9pQ0uSJWPQlg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:YjnoOA+3r++B07g73XdhYj6x3xb36IejWV0y3dJWsuRq9YZN,iv:p/C/H6cnhjDo0AFSvwp2inyapILdc406VYhPEsKW9tU=,tag:F7TNPPb1qA8AvZWfwQpn8A==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:ug5whUSP2k41Gmz/pFm5VWq12hWOcfzDs8gIo2hs5THvDL57RL8iOg==,iv:YznJBwYysFUuQiE2ecpZjXp7cHnLmIIDE6xWHmnTR68=,tag:pvI78wtJZcCK++1fzvpW7Q==,type:str]
sops:
    age:
        - recipient: age1dgw6l56j4qu7jnh06n9z7rpctgar3stk8hnxq3es9j88yqjpzdvqkrp7en
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYTZNRk9IL0hiVUhBc1l2
            dnJzcTJZbmdoc1RIRVNYeEJ0R3B4UG1LL0ZvCmdUbnpTVlVkTnZqVi82WWhXZy83
            L0VNNGZaSjU4cFdOZWFaQnNYLzd5a1kKLS0tIFErTHA5c1Nob3o4emFYS0V4QTNT
            N2NmYWhML0l4TEZXMENmMkVQRWo4MGcKTwQvE5oUghf+EGebhDmSslWNrHgzonxP
            xk6PjC5rH0FQMz2/1/Zvr4M0HXS+s5TIzgAyAH+u+CSfUT2UnhQvvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T09:49:10Z"
    mac: ENC[AES256_GCM,data:rGwBiUjgOtuV8oEggnUU2FGni5t1+gt6+m+ZvY8UUBnWSh/w5iNnKGN4bQpW3ib862tJgxFWWZSZeX4CJDeAxkCaE8hHeFZa67WGHUwsrdTLBujw++5qRQtUcW6J8+OfBg0R6VYdWMJialJ6FUZSEgiicFAjaUmhullbtJE6T3Q=,iv:sdz52PiH6gj2GpeFpYNGmUmOkidhMguD7xBKaVFX388=,tag:9AyXO2Kug1hUvgXc3j/YTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.0
